# Docker Compose V2形式
services:
  app:
    build: .
    ports:
      - "33000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
    command: npm run dev

networks:
  default:
    name: calendar_sync_network